version: 2.0
jobs:
  base:
    docker:
    - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/NoahOrberg/protobuf_langserver
    steps:
    - checkout
    - run:
        name: installation dep command
        command: go get -u github.com/golang/dep/cmd/dep
    - run:
        name: fetch dependencies
        command: make dep
    - run:
        name: installation (build)
        command: make install
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - base
